"""Add post-job fields to Booking

Revision ID: 0ae3a65cae31
Revises: 
Create Date: 2025-02-21 12:56:54.789268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae3a65cae31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('amount_charged', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('client_happy', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('asked_for_review', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('asked_for_review')
        batch_op.drop_column('client_happy')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('amount_charged')
        batch_op.drop_column('total_time')

    # ### end Alembic commands ###
