"""Replace access_stairs with pickup_access_stairs and dropoff_access_stairs

Revision ID: a768f3986968
Revises: 4675997e5e1c
Create Date: 2025-02-21 21:49:03.782584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a768f3986968'
down_revision = '4675997e5e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_access_stairs', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dropoff_access_stairs', sa.String(length=100), nullable=True))
        batch_op.drop_column('access_stairs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_stairs', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('dropoff_access_stairs')
        batch_op.drop_column('pickup_access_stairs')

    # ### end Alembic commands ###
