"""Initial postgres schema

Revision ID: d90172e56234
Revises: a768f3986968
Create Date: 2025-07-15 20:25:21.114894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90172e56234'
down_revision = 'a768f3986968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pickup_address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('dropoff_address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('start_time', sa.VARCHAR(length=50), nullable=True),
    sa.Column('hourly_rate', sa.FLOAT(), nullable=True),
    sa.Column('truck', sa.VARCHAR(length=50), nullable=True),
    sa.Column('men', sa.VARCHAR(length=100), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('estimated_time', sa.VARCHAR(length=50), nullable=True),
    sa.Column('booking_source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('parking_info', sa.VARCHAR(length=100), nullable=True),
    sa.Column('list_of_items', sa.TEXT(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('total_time', sa.VARCHAR(length=50), nullable=True),
    sa.Column('amount_charged', sa.FLOAT(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('client_happy', sa.VARCHAR(length=10), nullable=True),
    sa.Column('asked_for_review', sa.VARCHAR(length=10), nullable=True),
    sa.Column('pickup_access_stairs', sa.VARCHAR(length=100), nullable=True),
    sa.Column('dropoff_access_stairs', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
